In [2]:
import pandas as pd
import os
import numpy as np

In [3]:
df = pd.read_csv('C:\\Users\\mdw2685\\Desktop\\Projects\\early_tests\\Inverts_Taxon.csv')

C:\Users\mdw2685\AppData\Local\Temp\ipykernel_9180\894049766.py:1: DtypeWarning: Columns (6,7,8,9,10,13,16,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:\\Users\\mdw2685\\Desktop\\Projects\\early_tests\\Inverts_Taxon.csv')

In [14]:
df.head()

,taxonID,datasetID,parentNameUsageID,acceptedNameUsageID,originalNameUsageID,scientificName,scientificNameAuthorship,canonicalName,genericName,specificEpithet,...,namePublishedIn,taxonomicStatus,nomenclaturalStatus,taxonRemarks,kingdom,phylum,class,order,family,genus
0,8987139,c8227bb4-4143-443f-8cb2-51f9576aff14,1.0,NaN,NaN,"Stipecrinus Villanueva-Olea & Sour-Tovar, 2014","Villanueva-Olea & Sour-Tovar, 2014",Stipecrinus,Stipecrinus,NaN,...,"Villanueva-Olea, Rafael & Francisco Sour-Tovar...",accepted,NaN,NaN,Animalia,NaN,NaN,NaN,NaN,Stipecrinus
1,1,d7dddbf4-2cf0-4f39-9b2a-bb099caae36c,NaN,NaN,NaN,Animalia,NaN,Animalia,Animalia,NaN,...,NaN,accepted,NaN,NaN,Animalia,NaN,NaN,NaN,NaN,NaN
2,7961678,80b4b440-eaca-4860-aadf-d0dfdd3e856e,1.0,NaN,NaN,Liotheidae,NaN,Liotheidae,Liotheidae,NaN,...,"<i>Handb. Entomol.</i>, <b>2</b>(2): 436",accepted,NaN,NaN,Animalia,NaN,NaN,NaN,Liotheidae,NaN
3,8137953,80b4b440-eaca-4860-aadf-d0dfdd3e856e,1.0,NaN,NaN,Turbinoidae,NaN,Turbinoidae,Turbinoidae,NaN,...,NaN,accepted,NaN,NaN,Animalia,NaN,NaN,NaN,Turbinoidae,NaN
4,7758685,80b4b440-eaca-4860-aadf-d0dfdd3e856e,1.0,NaN,NaN,Danaididae,NaN,Danaididae,Danaididae,NaN,...,"<i>Acta Soc. Sci. fenn.</i>, <b>22</b>: 301",accepted,NaN,NaN,Animalia,NaN,NaN,NaN,Danaididae,NaN

In [7]:
df = df.rename(columns={'taxonID': 'id', 
                   'acceptedNameUsageID': 'accid', 
                   'taxonomicStatus': 'taxonomic_status', 
                   'canonicalName': 'canonical', 
                   'scientificName': 'validName',
                   'scientificNameAuthorship': 'authorship',
                   'taxonRank': 'taxon_rank',
                   'infraspecificEpithet': 'infraspecies',
                   }, errors="raise")

In [8]:
df['valid'] = np.where(df['taxonomicStatus'] == 'accepted', True, False)
df['source'] = 'gbif'

KeyError: 'taxonomicStatus'

In [9]:
df.head()

,id,datasetID,parentNameUsageID,accid,originalNameUsageID,validName,authorship,canonical,genericName,specificEpithet,...,nomenclaturalStatus,taxonRemarks,kingdom,phylum,class,order,family,genus,valid,source
0,8987139,c8227bb4-4143-443f-8cb2-51f9576aff14,1.0,NaN,NaN,"Stipecrinus Villanueva-Olea & Sour-Tovar, 2014","Villanueva-Olea & Sour-Tovar, 2014",Stipecrinus,Stipecrinus,NaN,...,NaN,NaN,Animalia,NaN,NaN,NaN,NaN,Stipecrinus,True,gbif
1,1,d7dddbf4-2cf0-4f39-9b2a-bb099caae36c,NaN,NaN,NaN,Animalia,NaN,Animalia,Animalia,NaN,...,NaN,NaN,Animalia,NaN,NaN,NaN,NaN,NaN,True,gbif
2,7961678,80b4b440-eaca-4860-aadf-d0dfdd3e856e,1.0,NaN,NaN,Liotheidae,NaN,Liotheidae,Liotheidae,NaN,...,NaN,NaN,Animalia,NaN,NaN,NaN,Liotheidae,NaN,True,gbif
3,8137953,80b4b440-eaca-4860-aadf-d0dfdd3e856e,1.0,NaN,NaN,Turbinoidae,NaN,Turbinoidae,Turbinoidae,NaN,...,NaN,NaN,Animalia,NaN,NaN,NaN,Turbinoidae,NaN,True,gbif
4,7758685,80b4b440-eaca-4860-aadf-d0dfdd3e856e,1.0,NaN,NaN,Danaididae,NaN,Danaididae,Danaididae,NaN,...,NaN,NaN,Animalia,NaN,NaN,NaN,Danaididae,NaN,True,gbif

In [10]:
df.to_csv('C:\\Users\\mdw2685\\Desktop\\Projects\\early_tests\\corrected_inverts_taxon.csv', index=False)